[2024-12-10T14:32:55.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T14:32:55.136+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-12-10T14:31:59.660667+00:00 [queued]>
[2024-12-10T14:32:55.143+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict manual__2024-12-10T14:31:59.660667+00:00 [queued]>
[2024-12-10T14:32:55.144+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-10T14:32:55.157+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict> on 2024-12-10 14:31:59.660667+00:00
[2024-12-10T14:32:55.164+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-10T14:32:55.166+0000] {standard_task_runner.py:72} INFO - Started process 113 to run task
[2024-12-10T14:32:55.166+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'manual__2024-12-10T14:31:59.660667+00:00', '--job-id', '1897', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpasf8n0d6']
[2024-12-10T14:32:55.167+0000] {standard_task_runner.py:105} INFO - Job 1897: Subtask predict
[2024-12-10T14:32:55.213+0000] {task_command.py:467} INFO - Running <TaskInstance: car_price_prediction.predict manual__2024-12-10T14:31:59.660667+00:00 [running]> on host 4b38f6471eac
[2024-12-10T14:32:55.304+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T14:31:59.660667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T14:31:59.660667+00:00'
[2024-12-10T14:32:55.305+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T14:32:55.306+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T14:32:55.306+0000] {logging_mixin.py:190} INFO - Current task name:predict state:running start_date:2024-12-10 14:32:55.136680+00:00
[2024-12-10T14:32:55.307+0000] {logging_mixin.py:190} INFO - Dag name:car_price_prediction and current dag run status:running
[2024-12-10T14:32:55.307+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T14:32:55.308+0000] {logging_mixin.py:190} INFO - Loading the model...
[2024-12-10T14:32:55.308+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 43, in predict
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 8, in load_model
    with open(model_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T14:32:55.324+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T14:32:55.325+0000] {logging_mixin.py:190} INFO - Task start:2024-12-10 14:32:55.136680+00:00 end:2024-12-10 14:32:55.324110+00:00 duration:0.18743
[2024-12-10T14:32:55.325+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): predict> dag:<DAG: car_price_prediction> dagrun:<DagRun car_price_prediction @ 2024-12-10 14:31:59.660667+00:00: manual__2024-12-10T14:31:59.660667+00:00, state:running, queued_at: 2024-12-10 14:31:59.681546+00:00. externally triggered: True>
[2024-12-10T14:32:55.326+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T14:32:55.326+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=predict, run_id=manual__2024-12-10T14:31:59.660667+00:00, execution_date=20241210T143159, start_date=20241210T143255, end_date=20241210T143255
[2024-12-10T14:32:55.345+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T14:32:55.346+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1897 for task predict ([Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'; 113)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 43, in predict
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 8, in load_model
    with open(model_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T14:32:55.384+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T14:32:55.404+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T14:32:55.406+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
